#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules/prisma/build/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules/prisma/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules/prisma/build/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules/prisma/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/prisma@5.9.0/node_modules:/mnt/c/Users/Maciej/AppData/Local/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../Users/Maciej/AppData/Local/pnpm/global/5/node_modules/prisma/build/index.js" "$@"
else
  exec node  "$basedir/../../../../../../Users/Maciej/AppData/Local/pnpm/global/5/node_modules/prisma/build/index.js" "$@"
fi
